# Generated by Django 4.0.3 on 2022-03-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
