# Generated by Django 4.0.3 on 2022-03-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0002_question_is_comment_useranswer_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('number',)},
        ),
    ]
