# Generated by Django 4.0.3 on 2022-03-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0006_remove_useranswer_answer_useranswer_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answers',
            field=models.ManyToManyField(blank=True, to='survey_api.answer', verbose_name='answers'),
        ),
    ]
